from . import cmd_start_record
from . import add_title
from . import add_text
from . import add_price
from . import add_photo
from . import add_direction
from . import add_conditions
from . import post_instruction
from . import publication_post